#!/usr/bin/env python3
"""
Generate the SOInsight classifier Modelfile from app/taxonomy.py.

The taxonomy is baked into the model's SYSTEM prompt, so it must never drift
from the taxonomy the application validates against — `is_valid(main, sub)`
rejects anything outside it, and a rejected classification costs a retry and
then falls back to Misuse / Noise. Generating the Modelfile from the same
module makes that drift impossible.

Usage (from the repo root):
    python models/generate_modelfile.py                      # default base model
    python models/generate_modelfile.py --base llama3.2:3b
    python models/generate_modelfile.py --num-ctx 16384
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.taxonomy import TAXONOMY  # noqa: E402

# Qwen2.5 3B follows "emit only JSON, use only these enum values" noticeably more
# reliably than similarly sized alternatives, which is the whole job here. Swap
# with --base if you prefer llama3.2:3b (a little weaker on strict JSON) or size
# up to a 7B if you have the headroom.
DEFAULT_BASE = "qwen2.5:3b-instruct"

# SOInsight's batch prompt measures ~3,561 tokens with a full 20-question batch
# (taxonomy + 16 few-shot examples + 20 x 300-char bodies). Ollama's default
# context is at or below that depending on version, and an overflowing prompt is
# truncated from the FRONT — which drops the taxonomy and the instructions and
# leaves the model classifying against nothing. 8192 leaves comfortable headroom.
DEFAULT_NUM_CTX = 8192

MODEL_NAME = "soinsight-classifier"


def taxonomy_block() -> str:
    lines: list[str] = []
    for main, subs in TAXONOMY.items():
        lines.append(f'  "{main}":')
        lines.extend(f'    - "{sub}"' for sub in subs)
    return "\n".join(lines)


def build_modelfile(base: str, num_ctx: int) -> str:
    pairs = sum(len(subs) for subs in TAXONOMY.values())
    return f'''# SOInsight classifier — generated by models/generate_modelfile.py
# Do not edit by hand; edit backend/app/taxonomy.py and regenerate.
#
# Base: {base}
# Taxonomy: {len(TAXONOMY)} main categories, {pairs} main/sub pairs.

FROM {base}

# Deterministic classification: the same question must land in the same category
# on every run, otherwise counts and patterns shift between Analysis runs over
# identical data.
PARAMETER temperature 0
PARAMETER top_p 1
PARAMETER top_k 1
PARAMETER seed 0
PARAMETER repeat_penalty 1

# Must exceed SOInsight's ~3.5k-token batch prompt. See the note in
# generate_modelfile.py for why an undersized context silently degrades results.
PARAMETER num_ctx {num_ctx}

# Classification output is short JSON; capping it stops a stuck model from
# generating until the context is exhausted.
PARAMETER num_predict 1024

# Stop the model padding valid JSON with prose.
PARAMETER stop "```"
PARAMETER stop "\\n\\n\\n"

SYSTEM """You are the classification engine for SOInsight, which analyses Stack
Overflow Enterprise questions to find recurring product and documentation problems.

You classify each question into EXACTLY ONE main category and ONE sub-category
from this fixed taxonomy. These strings are a closed set — the application
validates every value against it and discards anything that does not match
character for character.

TAXONOMY:
{taxonomy_block()}

RULES:
1. Output valid JSON and nothing else. No prose, no markdown fences, no
   commentary before or after.
2. Use only the exact strings above, including capitalisation, spacing, and
   punctuation such as the slash in "Security / Compliance".
3. The sub-category must belong to the main category you chose. Pairs from
   different main categories are invalid.
4. When asked for N questions, return a JSON array of exactly N objects, in the
   same order as the input. Never merge, skip, or reorder them.
5. Each object has exactly these keys: "main", "sub", "confidence" (0.0-1.0),
   "reason" (one short sentence).
6. Classify what the asker actually needs, not the surface topic. A question
   mentioning Kubernetes because the docs were unclear is Documentation, not
   Technical.
7. Use "Misuse / Noise" only for genuinely unusable content — empty or test
   posts, or an explicit duplicate. A vague but real problem is not noise.
8. Never invent a category. If uncertain, choose the closest valid pair and
   lower the confidence rather than inventing a label or returning null.
"""
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", default=DEFAULT_BASE, help=f"base model (default: {DEFAULT_BASE})")
    ap.add_argument(
        "--num-ctx", type=int, default=DEFAULT_NUM_CTX,
        help=f"context window (default: {DEFAULT_NUM_CTX})",
    )
    ap.add_argument(
        "--out", type=Path, default=Path(__file__).parent / "Modelfile",
        help="output path (default: models/Modelfile)",
    )
    args = ap.parse_args()

    if args.num_ctx < 4096:
        print(
            f"refusing to generate: --num-ctx {args.num_ctx} is below SOInsight's "
            "~3.5k-token batch prompt plus its response; the taxonomy would be "
            "truncated away at classification time.",
            file=sys.stderr,
        )
        return 1

    args.out.write_text(build_modelfile(args.base, args.num_ctx), encoding="utf-8")
    pairs = sum(len(subs) for subs in TAXONOMY.values())
    print(f"wrote {args.out}")
    print(f"  base    : {args.base}")
    print(f"  num_ctx : {args.num_ctx}")
    print(f"  taxonomy: {len(TAXONOMY)} main categories, {pairs} pairs")
    print(f"\nBuild it with:\n  ollama create {MODEL_NAME} -f {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
